### ISSUE TITLE
wrong stream data when resume from breakpoint

### ISSUE THREAD

**Issue by gneworld** [mihaigalos/tutorials#10]
https://github.com/mihaigalos/tutorials/blob/51d5e5e8f8baea68a8be6527eb51ec4e0775bbf7/rust/download_with_progressbar/src/main.rs#L47

hello, it only seek the file ptr to breakpoint position, but not seek the downloading stream data to right breakpoint position?
@mihaigalos

**Comment by gneworld** [comment]
@mihaigalos

**Comment by mihaigalos** [comment]
Hi. This is a tutorial demo.
For a fix to your particular problem, see the implementation in [aim](https://github.com/mihaigalos/aim/blob/66a8b6dfa1b0dcaba7b3c1d3d5142cf4461f9df5/src/https.rs#L61).
